version: '3.3'

services:

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 80:8000
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
    networks:
      - project


networks:
  project: