version: '3.3'

services:

  nginx:
    build:
      context: docker/nginx/
    ports:
      - 80:80
    depends_on:
      - web
    restart: always
    networks:
      - project

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8000:8000
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - project


networks:
  project: